import time
time.sleep(2)
print("Die Zeit ist um!!!")
print("Du hast 30 Sekunden Zeit. Viel Erfolg!!!")
print("Wie heißt die Hauptstadt von Deutschland?")
input("")
time.sleep(30)
print("Wieviele Sterne hat die europäische Flagge?")
input("")
time.sleep(30)
print("Wer war der erste Mann auf dem Mond?")
input("")
time.sleep(30)
print("Wer hat die Champions League im Jahre 2020 gewonnen?")
input("")
time.sleep(30)
print("In welchen Land befindet sich der schiefe Turm von Pisa?")
input("")
time.sleep(30)
print("Wer war der erste Präsident in Amerika?")
input("")
time.sleep(30)
print("Was trinken Kühe?")
print("")
time.sleep(30)
print("Wie viele Sterne hat die europäische Flagge?")
print("")
time.sleep(30)
print("Aus welchen Land stammt das Gericht Jalapenos?")
print("")
time.sleep(30)
print("Was bedeutet das Wort ,,Hardly´´ im Deutschen?")
print("")
time.sleep(30)
print("Deine Zeit ist um!!")
